language: c
compiler:
  - clang
  - gcc
dist: trusty
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check libevent-dev
  - sudo pip install -r requirements.txt
  - cd ~/build
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.7/libsodium-1.0.7.tar.gz
  - tar xzf libsodium-1.0.7.tar.gz
  - cd libsodium-1.0.7 && ./configure --prefix=/usr && make && sudo make install
  - cd ~/build
  - wget http://libbsd.freedesktop.org/releases/libbsd-0.7.0.tar.xz
  - tar xJf libbsd-0.7.0.tar.xz
  - cd libbsd-0.7.0 && ./configure --prefix=/usr --libdir=/lib/x86_64-linux-gnu && make && sudo make install
script:
  - mkdir ~/build/kickpass-build
  - cd ~/build/kickpass-build
  - cmake -DBUILD=Debug $TRAVIS_BUILD_DIR && make && make test ARGS="-V"
